- name: install
  with_items:
    - git
  package:
    name: '{{ item }}'
    state: present

- name: homeshick
  git:
    repo: https://github.com/andsens/homeshick.git
    dest: /root/.homesick/repos/homeshick

- name: castles
  with_items: '{{ root_castles }}'
  when: root_castles|default(None) != None
  git:
    repo: https://github.com/{{ item }}.git
    dest: /root/.homesick/repos/{{ item | basename }}

- name: links
  with_items: '{{ root_castles }}'
  when: root_castles|default(None) != None
  command: /root/.homesick/repos/homeshick/bin/homeshick -f -b -q link {{ item | basename }}

- name: sshkeys
  when: root_sshkeys|default(None) != None
  authorized_key:
    user: root
    key: '{{ root_sshkeys }}'
    path: /root/.ssh/instance_keys
    exclusive: yes
    state: present

- name: fetchkeys
  when: root_sshkeys|default(None) != None
  command: scw-fetch-ssh-keys --upgrade
