- name: service
  notify:
    - restart downloads
  template:
    src: service.j2
    dest: /etc/systemd/system/downloads.service

- name: default
  notify:
    - restart downloads
  template:
    src: default.j2
    dest: /etc/default/downloads

- name: start
  systemd:
    name: downloads
    state: started
    daemon_reload: yes
    masked: no
    enabled: yes
