- name: service
  notify:
    - restart docs
  template:
    src: service.j2
    dest: /etc/systemd/system/docs.service

- name: default
  notify:
    - restart docs
  template:
    src: default.j2
    dest: /etc/default/docs

- name: start
  systemd:
    name: docs
    state: started
    daemon_reload: yes
    masked: no
    enabled: yes
