- name: timer
  notify:
    - restart docker-gc
  template:
    src: timer.j2
    dest: /etc/systemd/system/docker-gc.timer

- name: service
  notify:
    - restart docker-gc
  template:
    src: service.j2
    dest: /etc/systemd/system/docker-gc.service

- name: start
  systemd:
    name: docker-gc.timer
    state: started
    daemon_reload: yes
    masked: no
    enabled: yes
