- name: service
  notify:
    - restart code
  template:
    src: service.j2
    dest: /etc/systemd/system/code.service

- name: default
  notify:
    - restart code
  template:
    src: default.j2
    dest: /etc/default/code

- name: start
  systemd:
    name: code
    state: started
    daemon_reload: yes
    masked: no
    enabled: yes
