- name: default
  notify:
    - restart agent
    - restart server
  template:
    src: default.j2
    dest: /etc/default/drone

- name: server
  include: server.yml
  when: drone_type == 'server' || drone_type == 'both'

- name: agent
  include: agent.yml
  when: drone_type == 'agent' || drone_type == 'both'
