- name: server service
  notify:
    - restart drone
  template:
    src: server.j2
    dest: /etc/systemd/system/drone.service

- name: server start
  systemd:
    name: drone
    state: started
    daemon_reload: yes
    masked: no
    enabled: yes
