- name: restart server
  when: drone_type == 'server' or drone_type == 'both'
  systemd:
    name: drone
    state: restarted
    daemon_reload: yes

- name: restart agent
  when: drone_type == 'agent' or drone_type == 'both'
  systemd:
    name: agent
    state: restarted
    daemon_reload: yes
