- name: service
  notify:
    - restart website
  template:
    src: service.j2
    dest: /etc/systemd/system/website.service

- name: default
  notify:
    - restart website
  template:
    src: default.j2
    dest: /etc/default/website

- name: start
  systemd:
    name: website
    state: started
    daemon_reload: yes
    masked: no
    enabled: yes
